Finish assigment-8
kulievtech/html pull request #1
Opened 2023-04-23 21:24 UTC by kulievtech

2023-04-23 21:39 UTC, aliramazon requested changes

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <input type="text" name="fullName" id="nameInput">
If asked fullName, the id attribute should be according to it like fullNameInput

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <h4>Are you attending?</h4>
Good heading selection. Liked it

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <input type="radio" name="attendingornot" id="yes">
id selection is bad. attendanceRadioInput

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <input type="radio" name="attendingornot" id="yes">
Bad casing., Should be camelCased, attendingOrNot

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <input type="radio" name="attendingornot" id="yes">
Add value as well.

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <input type="radio" name="attendingornot" id="no">
the same, camelCase name

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <label for="guestsnumberInput"></label>
id should be like numbrOfGuestsInput

2023-04-23 21:39 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <label for="mealInput">Choose your favorite meal</label>
id should be favoriteMealSelect

2023-04-23 21:56 UTC, aliramazon commented on assignments/assignment-8/index.html
> +        <h4>Are you attending?</h4>
Kudos for googling and finding out Legends

2023-04-25 16:23 UTC, kulievtech commented
Did you review it once again?

2023-04-27 08:07 UTC, aliramazon approved these changes

2023-04-27 08:07 UTC, aliramazon commented on assignments/assignment-8/assignment-6.html
> +        <title>RSVP</title>
Change to RSVP | Assignment - *,

2023-04-27 08:07 UTC, aliramazon commented on assignments/assignment-8/assignment-6.html
> +                <option value="nonVegetarian">Non-vegetarian</option>
I said capitalize, not cameCase it.

2023-04-27 17:56 UTC, merged